jobs:
  build_deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: installing AWS CLI
          command:
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run: cd ./app && npm install && npm run build
      - run: aws s3 sync ./app/build s3://blkgoldmusic.com

workflows:
  version: 2
  execute_bulk:
    jobs:
      - build_deploy